# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/kc/Data/EE2026/project/FDP/FDP.srcs/sources_1/ip/image_mem/image_mem.xci
# IP: The module: 'image_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/kc/Data/EE2026/project/FDP/FDP.srcs/sources_1/ip/image_mem/image_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /media/kc/Data/EE2026/project/FDP/FDP.srcs/sources_1/ip/image_mem/image_mem.xci
# IP: The module: 'image_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/kc/Data/EE2026/project/FDP/FDP.srcs/sources_1/ip/image_mem/image_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
