# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
<<<<<<< HEAD
set_property webtalk.parent_dir C:/Users/joelk/Documents/ee_files/EE2026/project/individual/combined/combined.cache/wt [current_project]
set_property parent.project_path C:/Users/joelk/Documents/ee_files/EE2026/project/individual/combined/combined.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/joelk/Documents/ee_files/EE2026/project/individual/combined/combined.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/joelk/Documents/ee_files/EE2026/project/individual/combined/combined.srcs/sources_1/imports/Desktop/Oled_Display.v
  C:/Users/joelk/Documents/ee_files/EE2026/project/individual/combined/combined.srcs/sources_1/new/Seven_Seg.v
  C:/Users/joelk/Documents/ee_files/EE2026/project/individual/combined/combined.srcs/sources_1/new/Task_P.v
  C:/Users/joelk/Documents/ee_files/EE2026/project/individual/combined/combined.srcs/sources_1/new/Task_Q.v
  C:/Users/joelk/Documents/ee_files/EE2026/project/individual/combined/combined.srcs/sources_1/new/Task_R.v
  C:/Users/joelk/Documents/ee_files/EE2026/project/individual/combined/combined.srcs/sources_1/new/taskS.v
  C:/Users/joelk/Documents/ee_files/EE2026/project/individual/combined/combined.srcs/sources_1/new/Top_Student.v
=======
set_property webtalk.parent_dir C:/Users/Joshy/EE2026_Basic_TaskP/EE2026_Project/project/individual/combined/combined.cache/wt [current_project]
set_property parent.project_path C:/Users/Joshy/EE2026_Basic_TaskP/EE2026_Project/project/individual/combined/combined.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Joshy/EE2026_Basic_TaskP/EE2026_Project/project/individual/combined/combined.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Joshy/EE2026_Basic_TaskP/EE2026_Project/project/individual/combined/combined.srcs/sources_1/imports/Desktop/Oled_Display.v
  C:/Users/Joshy/EE2026_Basic_TaskP/EE2026_Project/project/individual/combined/combined.srcs/sources_1/new/Seven_Seg.v
  C:/Users/Joshy/EE2026_Basic_TaskP/EE2026_Project/project/individual/taskP/taskP.srcs/sources_1/new/Task_P.v
  C:/Users/Joshy/EE2026_Basic_TaskP/EE2026_Project/project/individual/combined/combined.srcs/sources_1/new/Task_R.v
  C:/Users/Joshy/EE2026_Basic_TaskP/EE2026_Project/project/individual/combined/combined.srcs/sources_1/new/taskS.v
  C:/Users/Joshy/EE2026_Basic_TaskP/EE2026_Project/project/individual/combined/combined.srcs/sources_1/new/Top_Student.v
>>>>>>> fd621fe8c9ff5d80ae2144b110a39005ee77b47a
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
<<<<<<< HEAD
read_xdc C:/Users/joelk/Documents/ee_files/EE2026/project/individual/combined/combined.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/joelk/Documents/ee_files/EE2026/project/individual/combined/combined.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc]
=======
read_xdc C:/Users/Joshy/EE2026_Basic_TaskP/EE2026_Project/project/individual/combined/combined.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Joshy/EE2026_Basic_TaskP/EE2026_Project/project/individual/combined/combined.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc]
>>>>>>> fd621fe8c9ff5d80ae2144b110a39005ee77b47a

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
