webtalk_init -webtalk_dir /media/kc/Data/EE2026/project_3/project_3.sim/sim_1/behav/xsim/xsim.dir/lab3_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep  5 00:23:39 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d8cf2bf4e601583f956063f3a3055f02" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6dcce1e981b242fcac8267ce09dfe1dd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 PRO 8840U w/ Radeon 780M Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1896.788 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "32.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "12722235955 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "85.63_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114372_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1967429393 -regid "" -xml /media/kc/Data/EE2026/project_3/project_3.sim/sim_1/behav/xsim/xsim.dir/lab3_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/kc/Data/EE2026/project_3/project_3.sim/sim_1/behav/xsim/xsim.dir/lab3_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/kc/Data/EE2026/project_3/project_3.sim/sim_1/behav/xsim/xsim.dir/lab3_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
