# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/kc/Data/EE2026/project/FDP/FDP.srcs/sources_1/ip/display_clocks/display_clocks.xci
# IP: The module: 'display_clocks' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/kc/Data/EE2026/project/FDP/FDP.srcs/sources_1/ip/display_clocks/display_clocks_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_clocks'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/kc/Data/EE2026/project/FDP/FDP.srcs/sources_1/ip/display_clocks/display_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/kc/Data/EE2026/project/FDP/FDP.srcs/sources_1/ip/display_clocks/display_clocks_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/kc/Data/EE2026/project/FDP/FDP.srcs/sources_1/ip/display_clocks/display_clocks.xci
# IP: The module: 'display_clocks' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/kc/Data/EE2026/project/FDP/FDP.srcs/sources_1/ip/display_clocks/display_clocks_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/kc/Data/EE2026/project/FDP/FDP.srcs/sources_1/ip/display_clocks/display_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/kc/Data/EE2026/project/FDP/FDP.srcs/sources_1/ip/display_clocks/display_clocks_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
